DATA: 
  DATA_ROOT_PATH: "./dataset"
  IMAGE_SIZE: 64
  BATCH_SIZE: 64
  NUM_CHANNELS: 3
  SHOW_TRAIN_SAMPLE: False

  
SAVE: 
  SAVE_MODEL_PATH: "./saved_model/"
  SAVE_PLOTS_PATH: "./plots/"
  MODEL_CHECKPOINT: "./saved_model/generator_checkpoint_225.pt"

DISCRIMINATOR:
  DISCRIMINATOR_FEATURE_MAP_SIZE: 128
  DISCRIMINATOR_LR: 5e-5

GENERATOR:
  Z_SIZE: 100
  GENERATOR_FEATURE_MAP_SIZE: 128
  GENERATOR_LR: 2e-4

TRAIN:
  NUM_EPOCHS: 250
  BETA1: 0.5

RESUME_TRAINING: True
  

